version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: |
          docker build -t cecchisandrone/porterbot-controller:latest . 
          docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker buildx build --platform linux/arm/v7 -t cecchisandrone/porterbot-controller:latest --push .
  deploy:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - run:
          command: ssh -o StrictHostKeyChecking=no -l pi $PORTERBOT_SSH_HOST -p $PORTERBOT_SSH_PORT "docker pull cecchisandrone/porterbot-controller && docker rm -f porterbot-controller || true &&  docker run --name porterbot-controller -p 8080:8080 --privileged --device /dev/gpiomem --restart always --network porterbot --hostname porterbot-controller -d cecchisandrone/porterbot-controller"
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
